services:
  nats-jetstream:
    image: nats:latest
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management port
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf:ro
      - ./data:/data
    command: 
      - -js